channels:
  - conda-forge
dependencies:
  # dependencies
  - xtensor

  # optional dependencies
  - boost

  # build tools
  - cmake
  - ninja
  - setuptools_scm

  # Python API
  - python
  - numpy
  - xtensor-python

  # to run tests
  - catch2

  # build docs
  - doxygen
  - mathjax
