name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
        - runs-on: ubuntu-latest
          config: -DCMAKE_BUILD_TYPE=Release -DBUILD_ALL=1
        - runs-on: macos-latest
          config: -DCMAKE_BUILD_TYPE=Release -DBUILD_ALL=1
        - runs-on: windows-latest
          config: -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=1 -G Ninja -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    defaults:
      run:
        shell: bash -e -l {0}

    name: ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Clone this library
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Create conda environment
      uses: mamba-org/setup-micromamba@main
      with:
        environment-file: environment.yaml
        environment-name: myenv
        init-shell: bash
        cache-downloads: true
        create-args: >-
          ${{ runner.os == 'Windows' && 'clang_win-64' || '' }}

    - name: Export version of this library
      run: |
        LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
        echo "SETUPTOOLS_SCM_PRETEND_VERSION=$LATEST_TAG" >> $GITHUB_ENV

    - name: Configure using CMake
      run: cmake -Bbuild ${{ matrix.config }}

    - name: Build doxygen-docs
      if: runner.os == 'Linux'
      working-directory: build
      run: make html

    - name: Build C++
      working-directory: build
      run: cmake --build .

    - name: Run C++
      working-directory: build
      run: ctest --output-on-failure

    - name: Build and install Python module
      run: SKBUILD_CONFIGURE_OPTIONS="-DUSE_DEBUG=1" python -m pip install . -v --no-build-isolation

    - name: Run Python tests
      run: python -m unittest discover tests
