name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:

  standard:

    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - runs-on: ubuntu-latest
            config: -DBUILD_TESTS=1
            conda: environment.yaml
            prop: tests
          - runs-on: macos-latest
            config: -DBUILD_TESTS=1
            conda: environment.yaml
            prop: tests
          - runs-on: windows-latest
            config: -DBUILD_TESTS=1
            conda: environment.yaml
            prop: tests

    defaults:
      run:
        shell: bash -l {0}

    name: "${{ matrix.runs-on }} • x64 ${{ matrix.args }}"
    runs-on: ${{ matrix.runs-on }}

    steps:

    - name: Basic GitHub action setup
      uses: actions/checkout@v2

    - name: Set conda environment
      if: runner.os != 'Windows'
      uses: mamba-org/provision-with-micromamba@main
      with:
        environment-file: ${{ matrix.conda }}
        environment-name: myenv

    - name: Set conda environment
      if: runner.os == 'Windows'
      uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        environment-file: ${{ matrix.conda }}
        activate-environment: myenv
        auto-activate-base: false

    - name: Set dummy version
      run: echo "SETUPTOOLS_SCM_PRETEND_VERSION=ci" >> $GITHUB_ENV

    - name: Configure using CMake (!Windows)
      if: runner.os != 'Windows'
      run: cmake -Bbuild ${{ matrix.config }}

    - name: Configure using CMake (Windows)
      if: runner.os == 'Windows'
      run: |
        conda install -c conda-forge clang_win-64 ninja
        cmake -Bbuild -G Ninja ${{ matrix.config }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build C++ ${{ matrix.prop }}
      working-directory: build
      run: cmake --build .

    - name: Run C++ ${{ matrix.prop }}
      working-directory: build
      run: ctest --output-on-failure
